### ISSUE TITLE
centrifugo的api返回是{}，这个正常吗？

### ISSUE THREAD

**Issue by jingjie520** [xurwxj/centrifugal_cn_doc#1]
冒昧的请教一下，我用Docker启动的centrifugo，启动的命令
`docker run --name centrifugo -p 1083:8000   --ulimit nofile=65536:65536 -v ${PWD}/file:/centrifugo centrifugo/centrifugo centrifugo -c config.json`
我的config.json
`
{
  "secret": "secret",
  "api_key":"52idea",

  "admin":true,
  "admin_password": "password",
  "admin_secret": "secret",
  "debug":true,

  "namespaces": [
    {
      "name": "chat",
      "anonymous": false,
      "publish": true,
      "join_leave": true,
      "presence": true,
      "presence_stats": true,
      "history_size": 10,
      "history_lifetime": 60,
      "history_recover": true
    },
    {
      "name": "public",
      "anonymous": true,
      "publish": true,
      "join_leave": true,
      "presence": true,
      "presence_stats": true,
      "history_size": 10,
      "history_lifetime": 60,
      "history_recover": true
    }  
  ]
}

`

我启动centrifugo之后，用Restlet Client连接Servier Api ，不知道是否工作正常，想请教一下。
POST http://192.168.56.3:1083/api
HEADERS
Authorization: | apikey 52idea
Data：
{
    "method": "info",
    "params": {} 
}
Response：200 OK
`{"result":{"nodes":[{"uid":"4a16f31c-4027-48a2-b57e-b8463d3c5cc7","name":"8ea6d58a062a_8000","version":"2.2.1","num_clients":0,"num_users":0,"num_channels":0,"uptime":2377,"metrics":{"interval":60,"items":{"centrifuge.node.build.version.2.2.1":1,"centrifuge.node.messages_received_count.type.control":20,"centrifuge.node.messages_received_count.type.publication":0,"centrifuge.node.messages_sent_count.type.control":20,"centrifuge.node.messages_sent_count.type.publication":0,"centrifuge.node.num_channels":0,"centrifuge.node.num_clients":0,"centrifuge.node.num_users":0,"centrifugo.api.command_duration_seconds.count.method.broadcast.protocol.http":0,"centrifugo.api.command_duration_seconds.count.method.channels.protocol.http":0,"centrifugo.api.command_duration_seconds.count.method.history.protocol.http":0,"centrifugo.api.command_duration_seconds.count.method.info.protocol.http":10,"centrifugo.api.command_duration_seconds.count.method.presence.protocol.http":0,"centrifugo.api.command_duration_seconds.count.method.presence_stats.protocol.http":0,"centrifugo.api.command_duration_seconds.count.method.publish.protocol.http":0,"centrifugo.api.command_duration_seconds.quantile.50.method.broadcast.protocol.http":0.000084039,"centrifugo.api.command_duration_seconds.quantile.50.method.channels.protocol.http":0.000007671,"centrifugo.api.command_duration_seconds.quantile.50.method.history.protocol.http":0.000008287,"centrifugo.api.command_duration_seconds.quantile.50.method.info.protocol.http":0.000010379,"centrifugo.api.command_duration_seconds.quantile.50.method.presence.protocol.http":0.000007796,"centrifugo.api.command_duration_seconds.quantile.50.method.publish.protocol.http":0.000070127,"centrifugo.api.command_duration_seconds.quantile.99.method.broadcast.protocol.http":0.000119446,"centrifugo.api.command_duration_seconds.quantile.99.method.channels.protocol.http":0.000009117,"centrifugo.api.command_duration_seconds.quantile.99.method.history.protocol.http":0.000008287,"centrifugo.api.command_duration_seconds.quantile.99.method.info.protocol.http":0.000034959,"centrifugo.api.command_duration_seconds.quantile.99.method.presence.protocol.http":0.000007796,"centrifugo.api.command_duration_seconds.quantile.99.method.publish.protocol.http":0.000070127,"centrifugo.api.command_duration_seconds.quantile.999.method.broadcast.protocol.http":0.000119446,"centrifugo.api.command_duration_seconds.quantile.999.method.channels.protocol.http":0.000009117,"centrifugo.api.command_duration_seconds.quantile.999.method.history.protocol.http":0.000008287,"centrifugo.api.command_duration_seconds.quantile.999.method.info.protocol.http":0.000034959,"centrifugo.api.command_duration_seconds.quantile.999.method.presence.protocol.http":0.000007796,"centrifugo.api.command_duration_seconds.quantile.999.method.publish.protocol.http":0.000070127,"centrifugo.api.command_duration_seconds.sum.method.broadcast.protocol.http":0,"centrifugo.api.command_duration_seconds.sum.method.channels.protocol.http":0,"centrifugo.api.command_duration_seconds.sum.method.history.protocol.http":0,"centrifugo.api.command_duration_seconds.sum.method.info.protocol.http":0.00011727800000000017,"centrifugo.api.command_duration_seconds.sum.method.presence.protocol.http":0,"centrifugo.api.command_duration_seconds.sum.method.presence_stats.protocol.http":0,"centrifugo.api.command_duration_seconds.sum.method.publish.protocol.http":0,"go.gc.duration_seconds.count":1,"go.gc.duration_seconds.quantile.0":0.000016787,"go.gc.duration_seconds.quantile.100":0.000206146,"go.gc.duration_seconds.quantile.25":0.000022857,"go.gc.duration_seconds.quantile.50":0.00005981,"go.gc.duration_seconds.quantile.75":0.000122516,"go.gc.duration_seconds.sum":0.000022856999999999825,"go.goroutines":15,"go.info.version.go1.12.4":1,"go.memstats.alloc_bytes":3846792,"go.memstats.alloc_bytes_total":570552,"go.memstats.buck_hash_sys_bytes":1450998,"go.memstats.frees_total":9240,"go.memstats.gc_cpu_fraction":0.000005842758213684367,"go.memstats.gc_sys_bytes":2377728,"go.memstats.heap_alloc_bytes":3846792,"go.memstats.heap_idle_bytes":61333504,"go.memstats.heap_inuse_bytes":5120000,"go.memstats.heap_objects":18189,"go.memstats.heap_released_bytes":60637184,"go.memstats.heap_sys_bytes":66453504,"go.memstats.last_gc_time_seconds":1560017146.9790895,"go.memstats.lookups_total":0,"go.memstats.mallocs_total":4671,"go.memstats.mcache_inuse_bytes":3472,"go.memstats.mcache_sys_bytes":16384,"go.memstats.mspan_inuse_bytes":41904,"go.memstats.mspan_sys_bytes":49152,"go.memstats.next_gc_bytes":6762000,"go.memstats.other_sys_bytes":759042,"go.memstats.stack_inuse_bytes":655360,"go.memstats.stack_sys_bytes":655360,"go.memstats.sys_bytes":71762168,"go.threads":11,"process.cpu.seconds_total":0.06999999999999984,"process.max.fds":65536,"process.open.fds":7,"process.resident.memory_bytes":20434944,"process.start.time_seconds":1560014864.83,"process.virtual.memory_bytes":122486784,"process.virtual.memory_max_bytes":-1}}}]}}`

这是表示我的centrifugo配置的是正确的吗？

**Comment by xurwxj** [comment]
你跑的是v2.我翻译的文档是针对v1的。建议你直接在官方问版本2的问题
目前个人已经不考虑继续使用Centrifugo了，原因是维护成本和开源协议的原因。

**Comment by jingjie520** [comment]
好的，谢谢答复!
